debug = 374312160228147201
discord_token = "MTA2MTcxNzQ1MTk0MDgyNzMyNg.GExZoM.u-oUM7SjOhHB37Bw2q0GQyDoTt5WECxMLmMnq0"
max_filesize = 8

[channels_listening]
797145776110698506 = "https://discord.com/api/webhooks/1072441632982581278/jYIC8xmHAV2_GvCLtRoT-0QG1Ten1OlzMkwSwgd8mAwU73yBbULzOPJm2Crbu2w3dE-B"

[downloaders]
reddit = true
youtube = true
tumblr = false
tiktok = false
